pr:
    branches:
        include:
            - "main"
            - "demo"
            - just 

trigger:
    batch: "true"
    branches:
        include:
            - "main"
            - "demo"

# External resources, such as repositories, needed by this pipeline

# Variables used throughout the pipeline
variables:
    - name: IS_DEMO_BRANCH
      value: ${{ eq(variables['Build.SourceBranch'], 'temp') }}

    - name: IS_MAIN_BRANCH
      value: ${{ eq(variables['Build.SourceBranch'], 'refs/heads/demo') }}


        #
        # This pipeline is divided into four stages: UI_TESTS, UNIT_TESTS, BUILD_AND_PUBLISH, and DISTRIBUTE.
        # The first two stages are designed to run UI and Unit tests in parallel to optimize build times and resource utilization.
        # The BUILD_AND_PUBLISH stage depends on the successful completion of both testing stages before it can begin.
        # This ensures that we only build and publish our application if it passes all the automated tests.
        #The DISTRIBUTE stage depends on successful completion of BUILD_AND_PUBLISH and it will distribute the apk file to relevant group on microsoft app center.
        #
        # We are using different macOS image in UI_TEST stages to ensure compatibility and to take advantage of the specific toolsets

stages:
        - stage: UNIT_TESTS
          displayName: 'Unit Tests'
          dependsOn:
          jobs:
              - job: UnitTesting
                displayName: 'Unit Tests'
                condition: |
                  eq(variables.IS_MAIN_BRANCH, 'true')
                steps:
                   - script: echo hi how are you doing????
